services:
    _defaults:
        autowire: true
        autoconfigure: true

    Coffeincode\ContaoDownloadarchiveBundle\:
        resource: '../ContaoDownloadarchiveBundle/*'
        exclude: '../ContaoDownloadarchiveBundle/{ContaoManager,DependencyInjection,ContaoDownloadarchiveBundle.php}'

    Coffeincode\ContaoDownloadarchiveBundle\EventListener\DataContainer\DownloadarchiveitemLabelCallback:
        tags:
            - { name: contao.callback, table: tl_downloadarchiveitems, target: list.label.label_callback, method: __invoke }
