services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Psr\Log\LoggerInterface: '@monolog.logger.contao'

    Coffeincode\ContaoDownloadarchiveBundle\:
        resource: '../src/*'
        exclude: '../src/{ContaoManager,DependencyInjection,ContaoDownloadarchiveBundle.php}'

    Coffeincode\ContaoDownloadarchiveBundle\EventListener\DataContainer\DownloadarchiveitemLabelCallback:
        tags:
            - { name: contao.callback, table: tl_downloadarchiveitems, target: list.label.label_callback, method: __invoke }


    Coffeincode\ContaoDownloadarchiveBundle\EventListener\DataContainer\DownloadarchiveSaveCallback:
        tags:
            - { name: contao.callback, table: tl_downloadarchive, target: config.onsubmit_callback, method: __invoke }

    Coffeincode\ContaoDownloadarchiveBundle\Security\Voter\DataContainer\DownloadarchiveAccessVoter:
        tags: ['security.voter']